### ISSUE TITLE
fresh install, run  php public/index.php got PHP Fatal error:  No base path provided

### ISSUE THREAD

**Issue by samsonasik** [zfcampus/zf-apigility-skeleton#141]
Steps to reproduce:
1. Download apigility 1.4.0 from https://apigility.org/download
2. Create new API
3. Run command from `php public/index.php`
```
$ php public/index.php 
PHP Fatal error:  Uncaught Zend\View\Exception\RuntimeException: No base path provided in /Users/samsonasik/www/apigility/vendor/zendframework/zend-view/src/Helper/BasePath.php:38
Stack trace:
#0 [internal function]: Zend\View\Helper\BasePath->__invoke('/img/favicon.pn...')
#1 /Users/samsonasik/www/apigility/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(394): call_user_func_array(Object(Zend\View\Helper\BasePath), Array)
#2 /Users/samsonasik/www/apigility/module/Application/view/layout/layout.phtml(10): Zend\View\Renderer\PhpRenderer->__call('basePath', Array)
#3 /Users/samsonasik/www/apigility/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(502): include('/Users/samsonas...')
#4 /Users/samsonasik/www/apigility/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render()
#5 /Users/samsonasik/www/apigility/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#6 /Users/samsonasik/www/apigility/vendor/zend in /Users/samsonasik/www/apigility/vendor/zendframework/zend-view/src/Helper/BasePath.php on line 38

Fatal error: Uncaught Zend\View\Exception\RuntimeException: No base path provided in /Users/samsonasik/www/apigility/vendor/zendframework/zend-view/src/Helper/BasePath.php on line 38

Zend\View\Exception\RuntimeException: No base path provided in /Users/samsonasik/www/apigility/vendor/zendframework/zend-view/src/Helper/BasePath.php on line 38

Call Stack:
    0.0009     358312   1. {main}() /Users/samsonasik/www/apigility/public/index.php:0
    2.9370    4623032   2. Zend\Mvc\Application->run() /Users/samsonasik/www/apigility/public/index.php:43
    2.9374    4625112   3. Zend\Mvc\Application->completeRequest() /Users/samsonasik/www/apigility/vendor/zendframework/zend-mvc/src/Application.php:326
    2.9374    4625112   4. Zend\EventManager\EventManager->triggerEvent() /Users/samsonasik/www/apigility/vendor/zendframework/zend-mvc/src/Application.php:369
    2.9374    4625112   5. Zend\EventManager\EventManager->triggerListeners() /Users/samsonasik/www/apigility/vendor/zendframework/zend-eventmanager/src/EventManager.php:143
    2.9382    4710656   6. Zend\Mvc\View\Http\DefaultRenderingStrategy->render() /Users/samsonasik/www/apigility/vendor/zendframework/zend-eventmanager/src/EventManager.php:271
    3.1214    4954008   7. Zend\EventManager\EventManager->triggerEvent() /Users/samsonasik/www/apigility/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php:123
    3.1214    4954008   8. Zend\EventManager\EventManager->triggerListeners() /Users/samsonasik/www/apigility/vendor/zendframework/zend-eventmanager/src/EventManager.php:143
    3.1215    4955232   9. Zend\Mvc\View\Http\DefaultRenderingStrategy->render() /Users/samsonasik/www/apigility/vendor/zendframework/zend-eventmanager/src/EventManager.php:271
```

**Comment by samsonasik** [comment]
fixed by add : 
```
        "zendframework/zend-mvc-console": "^1.1",
```
should it in require or require-dev ?

**Comment by samsonasik** [comment]
I've created PR #144 for it.

**Comment by Naktibalda** [comment]
@samsonasik  Are you sure that adding and enabling Zend\Mvc\Console is enough?
I am still getting the same exception 'No base path provided'.

**Comment by samsonasik** [comment]
if you use latest `zendframework/zend-mvc-console:^1.1` , that should fixes the issue.

**Comment by Naktibalda** [comment]
I have `zendframework/zend-mvc-console (1.1.11)` installed, it still fails.

**Comment by webimpress** [comment]
@Naktibalda Do you have module `Zend\Mvc\Console` enabled and did you clear the cache (`data/cache` directory) ?

**Comment by Naktibalda** [comment]
Clearing cache was a missing step.

This is what I got now:
```
php public/index.php development enable
Zend Framework application
Usage:

Reason for failure: Invalid arguments or no arguments provided
```

**Comment by webimpress** [comment]
@Naktibalda Please check this out:
https://apigility.org/documentation/intro/updating-to-1-4#enabling-and-disabling-development-mode

**Comment by Naktibalda** [comment]
Thanks, that helped.
Both pieces of advice should be present in https://apigility.org/documentation/intro/installation

**Comment by weierophinney** [comment]
Closing per comments in #144
